version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts
    restart: on-failure
    ports:
      - "9990:8080"
      - "50000:50000"
    volumes:
      - /opt/jenkins/jenkins_home:/var/jenkins_home
      - /etc/localtime:/etc/localtime
    container_name: jenkins
  ssh-agent:
    image: jenkins/ssh-agent
    container_name: jenkins-agent
