server:
  http_listen_port: 9081
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: abfuzz
  static_configs:
  - targets:
    - localhost
    labels:
      job: abfuzz
      __path__: /var/logs/*-server/*.log
  pipeline_stages:
  - match:
      selector: '{job="abfuzz"}'
      stages:
        - regex: # level
            expression: '^\s*\S+\s+(?P<level>[a-zA-Z]+)'
        - regex: # project_id
            expression: '^.*"projectId"\s*:\s*"(?P<projectId>\w+)"'
        - regex: # fuzzing_id
            expression: '^.*("fuzzingId"\s*:\s*|"fuzzing"\s*:\s*\{\s*"id"\s*:\s*)"(?P<fuzzingId>\w+)"'
        - labels:
            level:
            projectId:
            fuzzingId:

- job_name: abfuzz-executions
  static_configs:
    - targets:
        - localhost
      labels:
        job: abfuzz-executions
        __path__: /var/logs/abfuzz/executions/*.log
  pipeline_stages:
  - json:
      expressions:
        level: level
        projectId: execution.projectId
        fuzzingId: execution.fuzzingId
  - labels:
      level:
      projectId:
      fuzzingId:
